development:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://localhost:5432/thingybase_development" } %>

test:
  adapter: async

production:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://localhost:5432/thingybase_production" } %>
