default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 0.0.0.0
  user: postgres
  timeout: 5000

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  adapter: production
