def parent_resources(name, **opts)
  resources name, **opts do
    scope module: name do
      yield
    end
  end
end

def batch_resources(resources_name)
  resources resources_name,
    param: :ids,
    ids: /(\d+,)+\d+/,
    controller: "#{resources_name}/batches",
    as: "#{resources_name}_batch"
end

Rails.application.routes.draw do
  # Special route that are generated by labels. These redirect to the associated item.
  get 'labels/:uuid', to: 'labels#redirect',
    uuid: /[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i

  resources :items do
    get :search, to: "items/searches#index"
    scope module: :items do
      resources :children, only: %i[index new]
      resources :labels, only: %i[create]
      resources :copies, only: %i[create new]
      resources :batches, only: %i[new create]
      resource :icon, only: %i[edit update]
    end
  end
  resources :members

  batch_resources :labels
  resources :labels do
    scope module: :labels do
      resources :items, only: %i[create]
    end
  end

  parent_resources :phone_number_claims do
    # No ID ; should this really be an
    # `interaction` resource? e.g.
    # `interaction :acknowledgements`
    resource :verification
  end
  resources :accounts do
    get :search, to: "accounts/searches#index"
    scope module: :accounts do
      resources :members
      resources :invitations
      resources :labels
      resources :items
    end
    collection do
      get :launch
    end
  end
  resources :invitations do
    scope module: :invitations do
      # No ID ; should this really be an
      # `interaction` resource? e.g.
      # `interaction :acknowledgements`
      resource :response
    end
    member do
      put :email
    end
  end

  resources :icons do
    member do
      get :light
      get :dark
    end
  end

  resources :users
  resource :user_resolution, only: %i[create new]
  resource :email_code_verification, only: %i[create new]
  resource :signup, only: %i[create new]
  resources :api_keys, except: %i[edit update]

  resource :session
  post "/auth/:provider/callback", to: 'sessions#create'
  get "/auth/:provider/callback", to: 'sessions#create'

  root to: 'pages#index'
end
